solid/data-interoperability-panel

data-validation/use-cases.md

Added a bit of a lead-in and some references to the data validation use cases document. Have started some rough draft use cases, but thought it would be helpful to push this ahead, separately.

add intro and references to data validation use cases

---

data-validation/use-cases.md

Use cases for common problem scenarios, then adding, processing, and modifying validations.

Initial round of use cases for data validation

---

problems-and-goals.md

Add data portability as a facet of general interoperability, and refined the language about controlling user-piloted applications. Some other minor grammar changes.

add portability, cleanup client restriction on problems and goals

---

proposals/ecosystem/ecosystem.ttl

Resolving a few minor issues in the TTL.

Updates to vocabulary to make valid TTL

---

proposals/specification/access-grants.bs
proposals/specification/access-receipts.bs
proposals/specification/application-registration.bs
proposals/specification/data-authorization.bs
proposals/specification/definitions.bs
proposals/specification/index.bs
proposals/specification/remote-data.bs
proposals/specification/security.bs

Update app registration to use cleaned up data model, resource hierarchy, operations, permission model section format.

Refactor app registration

---

proposals/primer/index.bs
proposals/primer/snippets/acme.example/67417bc2-5fc1-4e6e-91c4-eea1ead97d1c.ttl
proposals/primer/snippets/acme.example/f201471d-b1fb-40ad-9eac-867aaf09c3e5.ttl
proposals/primer/snippets/alice.example/4d594c61-7cff-484a-a1d2-1f353ee4e1e7.ttl
proposals/primer/snippets/alice.example/773605f0-b5bf-4d46-878d-5c167eac8b5d.ttl
proposals/primer/snippets/bob.example/0af793c1-8abc-441c-aacc-f78483b34217.ttl
proposals/primer/snippets/bob.example/4675444a-8a4d-46e1-abfe-85147e5a9b76.ttl
proposals/primer/snippets/prefixes.shex
proposals/primer/snippets/solidshapes.example/shapes/task.shex
proposals/primer/snippets/solidshapes.example/trees/project.ttl
proposals/primer/snippets/solidshapes.example/trees/task.ttl

unify snippets

---

proposals/primer/diagrams/home.alice.example.mmd
proposals/primer/diagrams/pro.alice.example.mmd
proposals/primer/images/overview.drawio.svg
proposals/primer/index.bs
proposals/primer/snippets/home.alice.example/0fd3daa3-dd6b-4484-826b-9ebaef099241.ttl
proposals/primer/snippets/home.alice.example/11f5ee6e-8ccf-4a70-96a8-f5174aaf9a27.ttl
proposals/primer/snippets/home.alice.example/2d3d97b4-a26d-434e-afa2-e3bc8e8e2b56.ttl
proposals/primer/snippets/home.alice.example/46fea403-8605-473b-a9a1-a86f50fb1633.ttl
proposals/primer/snippets/home.alice.example/72eb1958-5ad1-4268-96cb-739a71592cc0.ttl
proposals/primer/snippets/home.alice.example/92f43be4-d12c-4ca3-9bd6-c18e83167b2f.ttl
proposals/primer/snippets/home.alice.example/f6ccd3a4-45ea-4f98-8a36-98eac92a6720.ttl
proposals/primer/snippets/home.alice.example/f950bae5-247c-49b2-a537-b12cda8d5758.ttl
proposals/primer/snippets/prefixes.shex
proposals/primer/snippets/prefixes.ttl
proposals/primer/snippets/pro.alice.example/106a82aa-6911-4a7e-a49b-383cbaa9da66.ttl
proposals/primer/snippets/pro.alice.example/210cf13a-4082-487f-ab2b-ad54edb234a0.ttl
proposals/primer/snippets/pro.alice.example/4d594c61-7cff-484a-a1d2-1f353ee4e1e7.ttl
proposals/primer/snippets/pro.alice.example/4d713903-d114-4890-a87c-eaed50c33e5e.ttl
proposals/primer/snippets/pro.alice.example/576520a6-af5a-4cf9-8b40-8b1512b59c73.ttl
proposals/primer/snippets/pro.alice.example/5db9103b-392c-41a4-b823-100c213e24ff.ttl
proposals/primer/snippets/pro.alice.example/71e96aaa-f3dc-4263-97d6-a5b4c83524cb.ttl
proposals/primer/snippets/pro.alice.example/773605f0-b5bf-4d46-878d-5c167eac8b5d.ttl
proposals/primer/snippets/pro.alice.example/7a130c38-668a-4775-821a-08b38f2306fb.ttl
proposals/primer/snippets/pro.alice.example/aa97cee2-e698-4972-8f1c-0acf909f1377.ttl
proposals/primer/snippets/pro.alice.example/ccbd77ae-f769-4e07-b41f-5136501e13e7.ttl
proposals/primer/snippets/solidshapes.example/shapes/project.shex
proposals/primer/snippets/solidshapes.example/shapes/task.shex
proposals/primer/snippets/solidshapes.example/trees/project.ttl
proposals/primer/snippets/solidshapes.example/trees/task.ttl

[**rendered preview**](https://deploy-preview-119--data-interoperability-panel.netlify.app/primer/)
This PR includes minimum cleanup and marks many snippets as "needs to be updated".
It focuses on new layout for Alice's data, similar to one mentioned in #113 
I avoid getting into remote data registration. Next step will be few different data grants where Alice gives different combination of access for data she owns to specific application she wants to use.
I'm also introducing bridge/join resources where each *parent* resource can keep references to it's *children*.

Improved layout for data owned by alice

---

.gitignore
package.json
scripts/prepare-export.js

example of how it can be used for testing implementation: https://github.com/elf-pavlik/sai-js/commit/01cddbb3368587b62cdc5027fb50116b32e9abf6#diff-fad28ccbddffa13da72fa23b9c0c2cf80592ded7128c20cdffa64965e0203deaR4

npm package exports snippets from the primer

---

proposals/primer/index.bs
proposals/primer/snippets/auth.alice.example/0d0a1f64-39b1-438f-85f6-37cafee3ce21.ttl
proposals/primer/snippets/auth.alice.example/1cf3e08b-ffe2-465a-ac5b-94ce165cb8f0.ttl
proposals/primer/snippets/auth.alice.example/3fcef0f6-5807-4f1b-b77a-63d64df25a69.ttl
proposals/primer/snippets/auth.alice.example/bcf22534-0187-4ae4-b88f-fe0f9fa96659.ttl
proposals/primer/snippets/auth.alice.example/dd442d1b-bcc7-40e2-bbb9-4abfa7309fbe.ttl

This PR is still a draft, I'm making regular PR to have the [**rendered preview**](https://deploy-preview-121--data-interoperability-panel.netlify.app/primer/) available.
I'll comment again once it's ready to merge.

Projectron - Access Grant & Access Receipt

---

proposals/primer/snippets/auth.alice.example/3fcef0f6-5807-4f1b-b77a-63d64df25a69.ttl
proposals/primer/snippets/auth.alice.example/dd442d1b-bcc7-40e2-bbb9-4abfa7309fbe.ttl
proposals/specification/access-grants.bs
proposals/specification/index.bs

Following up on #124 
`proposals/specification/access-grants.bs` has tons of changes just because my editor auto-removed a ton of trailing white spaces.
Only actual change adds issue linking to github https://github.com/solid/data-interoperability-panel/compare/main...elf-pavlik:data-grant?expand=1#diff-e301eb398ba32b93a1bdc3fea7294f6f8be8f440cafe9a8e01e88733d71bb60dR536

Use Data Grant with InheritInstances scope

---

package.json
proposals/primer/snippets/solidshapes.example/trees/project.ttl
scripts/validate-snippets.js

`npm test` validates data snippets
i haven't setup github action, we ca do it as next step

validate snippets (turtle)

---

proposals/primer/index.bs
proposals/primer/snippets/home.alice.example/0fd3daa3-dd6b-4484-826b-9ebaef099241.ttl
proposals/primer/snippets/home.alice.example/11f5ee6e-8ccf-4a70-96a8-f5174aaf9a27.ttl
proposals/primer/snippets/home.alice.example/92f43be4-d12c-4ca3-9bd6-c18e83167b2f.ttl
proposals/primer/snippets/home.alice.example/f6ccd3a4-45ea-4f98-8a36-98eac92a6720.ttl
proposals/primer/snippets/pro.alice.example/4d594c61-7cff-484a-a1d2-1f353ee4e1e7.ttl
proposals/primer/snippets/pro.alice.example/5db9103b-392c-41a4-b823-100c213e24ff.ttl
proposals/primer/snippets/pro.alice.example/773605f0-b5bf-4d46-878d-5c167eac8b5d.ttl
proposals/primer/snippets/pro.alice.example/7a130c38-668a-4775-821a-08b38f2306fb.ttl
proposals/primer/snippets/pro.alice.example/aa97cee2-e698-4972-8f1c-0acf909f1377.ttl
proposals/primer/snippets/pro.alice.example/ccbd77ae-f769-4e07-b41f-5136501e13e7.ttl
proposals/primer/snippets/solidshapes.example/shapes/project.shex
proposals/primer/snippets/solidshapes.example/trees/project.ttl

I'm opening this draft PR just as a reference for what I should be able to implement Data Grant with `InheritsInstances` against. Actually I will test code using snippets from this branch.
Once we clarify how to expand prefixes in shape paths and possibly some other issues I will be able to update the implementation. I'll also create issues to track possible problems with using shape path.
We should also be able to discuss them tomorrow during panel meeting and on Wednesday during TS implementation meeting.

change shape path to referenced type and reference predicate

---

proposals/specification/access-grants.bs
proposals/specification/interop.ttl

This PR makes vocab validate and fixes capitalization of `rdf:Property`

Vocab updates

---

proposals/api/access-grants.bs
proposals/api/data-authorization.bs
proposals/specification/access-grants.bs
proposals/specification/access-needs.bs
proposals/specification/interop.shex
proposals/specification/interop.tree
proposals/specification/interop.ttl
proposals/specification/snippets/alice.example/08c5ae76-6c83-46f8-8e1d-eb14219e7f5f.ttl
proposals/specification/snippets/alice.example/ab3d0023-3860-4358-ae33-8d3af1097b9d.ttl
proposals/specification/snippets/projectron.example/projectron.example.ttl

Removes explicit "Reference" classes per #124. Also was an opportune time to add the dataOwner to Data Grants per #140.
Resolves #124.
Resolves #140.

Optimize referenced access needs and data grants

---

proposals/specification/access-consents.bs
proposals/specification/interop.shex
proposals/specification/snippets/alice.example/27eae14b.ttl
proposals/specification/snippets/alice.example/2ae35a57.ttl
proposals/specification/snippets/alice.example/4460dce3.ttl
proposals/specification/snippets/alice.example/47e07897.ttl
proposals/specification/snippets/alice.example/5ad22737.ttl
proposals/specification/snippets/alice.example/731b43ec.ttl
proposals/specification/snippets/alice.example/b6e125b8.ttl
proposals/specification/snippets/alice.example/cce01253.ttl
proposals/specification/snippets/alice.example/d577d117.ttl
proposals/specification/snippets/alice.example/e2765d6c.ttl
proposals/specification/snippets/bob.example/05f60b20.ttl
proposals/specification/snippets/jose.example/85b51e6a.ttl

Make consent records immutable

---

proposals/specification/interop.shex

Optimize shapes following editorial review

---

proposals/specification/interop.tree

Optimize shape trees following editorial review

---

proposals/specification/interop.ttl

the first commit for discussing details inline

vocab review

---

proposals/specification/access-consents.bs
proposals/specification/interop.shex
proposals/specification/snippets/alice.example/fa6d6553.ttl

specification: use agent registration discovery after receiving access receipt

---

proposals/specification/access-consents.bs
proposals/specification/interop.shex
proposals/specification/interop.ttl

Retain consent history

---

proposals/specification/access-consents.bs
proposals/specification/data-registrations.bs
proposals/specification/interop.shex
proposals/specification/interop.ttl
proposals/specification/snippets/alice.example/consents.ttl
proposals/specification/snippets/work.alice.example/data-registry.ttl

- Removes erroneous `hasDataResource` property
- Use `hasDataRegistration` instead of `hasRegistration` for `DataRegistry`
- Use `hasAccessConsent` instead of `hasRegistration` for `AccessConsentRegistry`

Adjust various properties

---

proposals/specification/access-authorizations.bs
proposals/specification/access-needs.bs
proposals/specification/agent.bs
proposals/specification/data-authorization.bs

diff which **ignores white spaces**: https://github.com/solid/data-interoperability-panel/pull/257/files?diff=unified&w=1
rendered preview: https://deploy-preview-257--data-interoperability-panel.netlify.app/specification/
We discussed doing that before we make PR with a snapshot of FPWD to solidproject.org/TR/sai
* #210 
* #138 
* #171 
* #232 
* #252 
* #243 
* #237 
* #214 
* #177 
* #221 
* #256 
* #223 
* #222 
* #186 
* #174

added issues inline

---

proposals/specification/diagrams/social-agent-shares-access.seq.mmd

This diagram works out the third of the authorization flows [section 7.1](https://solid.github.io/data-interoperability-panel/specification/#authorization-flows): Social Agent Shares Access. Feedback is welcome!

Add authz flow diagram for social agent sharing access

---

meetings/2022-11-21.md

just noticed the [hackmd](https://hackmd.io/gQ_lqLMwRKSgqynCo6t5pQ) was not yet put in a PR

minutes 2022-11-21
